connectors:
  - connector_id: 'BQConnector'
    label: 'BigQuery'
    export_id: 'bigquery_connector'
    category: 'data'
    icon: './img/BQConnector.jpg'
  - connector_id: 'DuckConnector'
    label: 'DuckDB'
    export_id: 'duckdb_connector'
    category: 'data'
    icon: './img/DuckConnector.jpg'
  - connector_id: 'ExcelConnector'
    label: 'Excel'
    export_id: 'excel_connector'
    category: 'data'
    icon: './img/ExcelConnector.jpg'
  - connector_id: 'CSVConnector'
    label: 'CSV'
    export_id: 'csv_connector'
    category: 'data'
    icon: './img/CSVConnector.jpg'
  - connector_id: 'PythonConnector'
    label: 'Python実行'
    export_id: 'python_connector'
    category: 'data'
    icon: './img/PythonConnector.jpg'
  - connector_id: 'DataintegrationConnector'
    label: 'データ加工'
    export_id: 'dataintegration_connector'
    category: 'data'
    icon: './icons/brick.svg'
  - connector_id: 'VectorConnector'
    label: 'VectorDB'
    export_id: 'vector_connector'
    category: 'data'
    icon: './icons/vectordb.svg'
  - connector_id: 'ShellConnector'
    label: 'Shell'
    export_id: 'shell_connector'
    category: 'workflow'
    icon: './icons/code.svg'
  - connector_id: 'WindowsConnector'
    label: 'Windows操作'
    export_id: 'windows_connector'
    category: 'workflow'
    icon: './img/WindowsConnector.jpg'
  - connector_id: 'SeleniumConnector'
    label: 'Selenium'
    export_id: 'selenium_connector'
    category: 'workflow'
    icon: './img/SeleniumConnector.jpg'
  - connector_id: 'ChromeConnector'
    label: 'Chrome'
    export_id: 'chrome_connector'
    category: 'workflow'
    icon: './icons/web.svg'
  - connector_id: 'PlotlyConnector'
    label: 'Plotly'
    export_id: 'plotly_connector'
    category: 'workflow'
    icon: './img/PlotlyConnector.jpg'
