execution_metadata_columns:
  - 'job_id'
  - 'target'
  - 'path'
  - 'executed_at'
policies:
  - data_area_policy_id: 'data.input'
    schema: 'no_rename'
    schema_json: 'no_rename'
    data_output: 'data_body'
    log: 'common'
  - data_area_policy_id: 'data.transform'
    schema: 'readonly'
    schema_json: 'readonly'
    data_output: 'data_body'
    log: 'common'
  - data_area_policy_id: 'data.output'
    schema: 'editable'
    schema_json: 'editable'
    data_output: 'execution_metadata'
    log: 'common'
  - data_area_policy_id: 'workflow.static'
    schema: 'readonly'
    schema_json: 'readonly'
    data_output: 'data_body'
    log: 'common'
  - data_area_policy_id: 'workflow.dynamic'
    schema: 'readonly'
    schema_json: 'readonly'
    data_output: 'execution_metadata'
    log: 'common'
  - data_area_policy_id: 'workflow.control'
    schema: 'readonly'
    schema_json: 'readonly'
    data_output: 'execution_metadata'
    log: 'common'
  - data_area_policy_id: 'workflow.control.loop'
    schema: 'readonly'
    schema_json: 'readonly'
    data_output: 'data_body'
    log: 'common'
